version: 0.2
phases:
  install:
    commands:
      - echo "Installing dependencies"
      - npm install
  pre_build:
    commands:
      - echo Running linting and security scan...
      - npm install eslint
      - npx eslint . || true
      - echo Running tests...
      - npm test || echo "Tests failed but continuing for demo"
  build:
    commands:
      - echo "Building app"
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - "**/*"
  discard-path: no
